# Generated by Django 3.2.10 on 2022-02-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weather.user')),
                ('unit', models.CharField(choices=[('Standard', 'Standard'), ('Metric', 'Metric'), ('Imperial', 'Imperial')], max_length=64, verbose_name='Unit:')),
                ('cities', models.ManyToManyField(related_name='cities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
