# Generated by Django 3.2.10 on 2022-02-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cities',
            field=models.ManyToManyField(related_name='cities', to='weather.City'),
        ),
    ]
