# Generated by Django 3.2.10 on 2022-02-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_preferences_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='unit',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Metric', 'Metric'), ('Imperial', 'Imperial')], default='Standard', max_length=64, verbose_name='Unit:'),
        ),
    ]
