# Generated by Django 3.2.10 on 2022-02-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_preferences_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='cities', to='weather.City'),
        ),
    ]
