# Generated by Django 3.2.10 on 2022-02-04 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_preferences_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=64),
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
