# Generated by Django 3.2.10 on 2022-02-04 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20220203_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='cities',
        ),
        migrations.AddField(
            model_name='city',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
