# Generated by Django 3.2.10 on 2022-02-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20220204_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.FloatField(),
        ),
    ]
