# Generated by Django 3.2.10 on 2022-02-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20220204_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='city',
            name='info',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='city',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
