# Generated by Django 3.2.10 on 2022-02-05 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20220205_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='info',
        ),
        migrations.RemoveField(
            model_name='city',
            name='summary',
        ),
    ]
